# -*- coding: utf-8 -*-
"""Projeto_Imobiliaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYrHo3YiFMBz7PebVWc7LivJYt-CroB6

# Importando dados
"""

import pandas  as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
df = pd.read_csv(url, sep= ';')
df.head()

"""# 7 primeiros resultados de nosso DataFrame"""

df.head(7)

"""# 3 Ultimo resultados de nossa DataFRame"""

df.tail(3)

df.shape

df.info()

df['Valor'].describe()

"""# Qual Valor médido por tipo de Imovel"""

preco_medio = df.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

preco_medio.plot(kind='barh', figsize=(10, 6), color='blue')

imoveis_comerciais = ['Conjunto Comercial/Sala',
                      'Prédio Inteiro', 'Loja/Salão',
                      'Galpão/Depósito/Armazém',
                      'Casa Comercial', 'Terreno Padrão',
                      'Loja Shopping/ Ct Comercial',
                      'Box/Garagem', 'Chácara',
                      'Loteamento/Condomínio', 'Sítio',
                      'Pousada/Chalé', 'Hotel', 'Indústria']

df = df.query('@imoveis_comerciais not in Tipo')
df['Tipo'].unique()

preco_medio = df.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

preco_medio.plot(kind='barh', figsize=(10, 6), color='blue')

df['Tipo'].value_counts(normalize=True).sort_values(ascending=True)

porcentagem_Tipo =df['Tipo'].value_counts(normalize=True).sort_values(ascending=True)
porcentagem_Tipo.plot(kind='bar', figsize=(10, 6), color='blue')

df = df.query('Tipo == "Apartamento"')
df.head()

"""# Removovendo dados NULO"""

df.isnull().sum()

# movendo zero para todos os campos Nulo , utilizando o metodo fillna()
df = df.fillna(0)
df.isnull().sum()

remover_linhas = df.query('Condominio == 0 | Valor == 0').index

df.drop(remover_linhas, axis=0 , inplace=True)

df.query('Condominio == 0 | Valor == 0')

df.Tipo.unique()

df.drop('Tipo', axis=1 , inplace=True)

df.head()