# -*- coding: utf-8 -*-
"""Projeto_Imobiliaria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYrHo3YiFMBz7PebVWc7LivJYt-CroB6

# Importando dados
"""

import pandas  as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
df = pd.read_csv(url, sep= ';')
df.head()

"""# 7 primeiros resultados de nosso DataFrame"""

df.head(7)

"""# 3 Ultimo resultados de nossa DataFRame"""

df.tail(3)

df.shape

df.info()

df['Valor'].describe()

"""# Qual Valor médido por tipo de Imovel"""

preco_medio = df.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

preco_medio.plot(kind='barh', figsize=(10, 6), color='blue')

imoveis_comerciais = ['Conjunto Comercial/Sala',
                      'Prédio Inteiro', 'Loja/Salão',
                      'Galpão/Depósito/Armazém',
                      'Casa Comercial', 'Terreno Padrão',
                      'Loja Shopping/ Ct Comercial',
                      'Box/Garagem', 'Chácara',
                      'Loteamento/Condomínio', 'Sítio',
                      'Pousada/Chalé', 'Hotel', 'Indústria']

df = df.query('@imoveis_comerciais not in Tipo')
df['Tipo'].unique()

preco_medio = df.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

preco_medio.plot(kind='barh', figsize=(10, 6), color='blue')

df['Tipo'].value_counts(normalize=True).sort_values(ascending=True)

porcentagem_Tipo =df['Tipo'].value_counts(normalize=True).sort_values(ascending=True)
porcentagem_Tipo.plot(kind='bar', figsize=(10, 6), color='blue')

df = df.query('Tipo == "Apartamento"')
df.head()

"""# Removovendo dados NULO"""

df.isnull().sum()

# movendo zero para todos os campos Nulo , utilizando o metodo fillna()
df = df.fillna(0)
df.isnull().sum()

remover_linhas = df.query('Condominio == 0 | Valor == 0').index

df.drop(remover_linhas, axis=0 , inplace=True)

df.query('Condominio == 0 | Valor == 0')

df.Tipo.unique()

df.drop('Tipo', axis=1 , inplace=True)

df.head()

"""#Apartamento que possui um quarto é aluguel menor que R$ 1200,00"""

#Filtrando todos apartamentos que tem 1 Quarto.
quartos = df['Quartos'] == 1
df[quartos]

# filtrando todos os Valores menor que R$1200,00
valores = df['Valor' ] < 1200
df[valores]

# filtrando Apartamento com 1 quarta e que são menores que R$1200,00
filtro_final = df[quartos & valores]
filtro_final

# Armazenando o Resutado em outro DataFrame
df_01 = filtro_final

"""
# Apartamentos que tenham 2 quartos , aluguel menor que R$3000,00 e com a area maior que 70"""

selecao = (df['Quartos'] >= 2) & (df['Valor'] < 3000) & (df['Area'] > 70)
df[selecao]

df02 = df[selecao]

"""# Salvando Dados"""

df.to_csv('dados_apartamento.csv',index=False)

pd.read_csv('dados_apartamento.csv')

df.to_csv('dados_apartamento.csv', index=False, sep=';')

pd.read_csv('dados_apartamento.csv', sep=';')

"""#Analisando dados
Criando colunas Numericas
"""

# importando toda a base via url , arquivo csv
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
df = pd.read_csv(url, sep= ';')
df.head()

# criando a coluna Valor por mês
df['valor_mes'] = df['Valor'] + df['Condominio']
df.head()

# criando coluna valor por Ano
df['valor_ano'] = df['valor_mes'] * 12 + df['IPTU']
df.head()

"""# Criando colunas categóricas"""

df['Descricao'] = df['Tipo'] + ' em ' + df['Bairro'] + '  com ' +\
                  df['Quartos'].astype(str) + ' Quarto(s)  e ' +\
                  df['Vagas'].astype(str) + ' Vagas'
df.head()

df['Possui_Suites'] = df['Suites'].apply(lambda x: 'Sim' if x > 0 else 'Não')
df.head()

"""# Salvando Arquivo modificado para os Devs"""

df.to_csv('dados_completo_dev.csv', index=False , sep=';')

pd.read_csv('dados_completo_dev.csv', sep=';')